package com.picassos.noted.constants;

public class RequestCodes {
    public static final int REQUEST_CODE_TEXT_TO_SPEECH = 50;
    public static final int REQUEST_CODE_UPDATE_NOTE_OK = 51;
    public static final int REQUEST_DELETE_NOTE_CODE = 52;
    public static final int REQUEST_DISCARD_NOTE_CODE = 53;
    public static final int REQUEST_VIEW_NOTE_IMAGE = 54;
    public static final int REQUEST_VIEW_NOTE_VIDEO = 55;
    public static final int REQUEST_REMOVE_NOTE_IMAGE_CODE = 56;
    public static final int REQUEST_REMOVE_NOTE_VIDEO_CODE = 57;
    public static final int REQUEST_CODE_ADD_NOTE_OK = 58;
    public static final int REQUEST_SET_PIN_CODE = 90;
    public static final int REQUEST_CODE_VIEW_NOTE_OK = 59;
    public static final int INTENT_AUTH_REQUEST_CODE = 60;
    public static final int REQUEST_DELETE_TODO_CODE = 61;
    public static final int REQUEST_MARK_TODO_CODE = 62;
    public static final int REQUEST_SAVE_TODO_CODE = 63;
    public static final int REQUEST_VIEW_TODO_CODE = 64;
    public static final int REQUEST_CREATE_LIST_CODE = 65;
    public static final int REQUEST_UNARCHIVE_NOTE = 66;
    public static final int REQUEST_STORAGE_PERMISSION_CODE = 67;
    public static final int REQUEST_CAMERA_PERMISSION_CODE = 68;
    public static final int REQUEST_SELECT_IMAGE_CODE = 69;
    public static final int REQUEST_SELECT_IMAGE_FROM_GALLERY_CODE = 70;
    public static final int REQUEST_CAMERA_IMAGE_CODE = 71;
    public static final int REQUEST_SELECT_VIDEO_FROM_GALLERY_CODE = 72;
    public static final int REQUEST_UPDATE_LIST_CODE = 73;
    public static final int REQUEST_ACTION_TODO_CODE = 74;
    public static final int REQUEST_DELETE_ALL_COMPLETED_TASKS_CODE = 75;
    public static final int CHOOSE_SORT_BY_A_TO_Z = 76;
    public static final int CHOOSE_SORT_BY_Z_TO_A = 77;
    public static final int CHOOSE_SORT_BY_DEFAULT = 78;
    public static final int REQUEST_ADD_CATEGORY_CODE = 79;
    public static final int REQUEST_EDIT_CATEGORY_CODE = 80;
    public static final int REQUEST_CHOOSE_CATEGORY_CODE = 81;
    public static final int CHOOSE_OPTION_REQUEST_CODE = 82;
    public static final int REQUEST_MOVE_TASK_CODE = 83;
    public static final int REQUEST_CODE_UNLOCK_NOTE = 84;
    public static final int REQUEST_REMOVE_PIN_CODE = 85;
    public static final int REQUEST_UPDATE_PIN_CODE = 86;
    public static final int REQUEST_RESTORE_NOTE_CODE = 87;
    public static final int REQUEST_DELETE_NOTE_PERMANENTLY_CODE = 89;
    public static final int REQUEST_UNLOCK_NOTE_CODE = 90;
    public static final int REQUEST_LOCK_NOTE_CODE = 91;
    public static final int REQUEST_ARCHIVE_NOTE_CODE = 92;
}
